### ISSUE TITLE
Backblaze b2 cloud Uploading Large files (9GB and more) not working 

### ISSUE THREAD

**Issue by showmack3** [obregonco/backblaze-b2#5] opened 2019-12-11 05:42 UTC
Hi,

Thanks for making it to work with PHP 7.0.
I'm using this from past 1 week and I am getting an error which I cannot handle even if place try catch blocks also...

Error:
![BackBlaze Service Unavailable - 500 or 503 Error while uploading Large Files like 9GB and more](https://user-images.githubusercontent.com/14347711/70594240-de681a00-1c05-11ea-9e52-7cda4ce229ad.PNG)

I need to upload files like 9GB and more in size. But I am always getting the error "500 or 503 Service Unavailable error was encountered while trying to upload files like 9GB or more".

I've placed try catch blocks to handle errors but whenever the errors like 500 or 503 arrived then It stops all the process and we cannot handle these errors.

I'm unable to upload Large file like 5GB, 9GB or 20 GB files. 
After I have tried many times I can upload 5GB. But I tried 9GB files 50 times to upload and same error is returning.

Can anyone please look into it and resolve it ASAP.
Or Please guide me how to resolve these issues.

Thanks

**Comment by robregonm** [comment] 2021-08-03 17:45
After some trial and error, it seems that this is being caused by some timeout.
In this case, I suggest moving this to background processing.

**Closed by robregonm** 2021-08-03 17:45 UTC
